import { PrismaClient } from "@prisma/client";

const foods = [
  {
    name: "Chicken Inasal",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 150,
    description: "Grilled chicken with a tangy marinade — a Filipino favorite.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["chicken", "filipino", "grilled"],
  },
  {
    name: "Roasted Chicken",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 180,
    description: "Classic roasted chicken — great for sharing with the group.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["chicken", "roasted", "shareable"],
  },
  {
    name: "Fried Chicken",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 180,
    description: "Crispy fried chicken that never disappoints.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["chicken", "fried", "comfort"],
  },
  {
    name: "Chicken Adobo",
    emoji: "🍲",
    category: "chicken",
    estimatedPricePerPerson: 140,
    description: "Classic Filipino adobo — savory, garlicky, and comforting.",
    moods: ["hungry", "filling", "budget"],
    tags: ["chicken", "filipino", "adobo"],
  },
  {
    name: "Chicken Joy",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 160,
    description: "The iconic crispy chicken meal everyone knows.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["chicken", "fastfood"],
  },
  {
    name: "Cheeseburger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 170,
    description: "Juicy burger with cheese — simple and satisfying.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["burger", "beef", "fastfood"],
  },
  {
    name: "Double Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 220,
    description: "Two patties for when one just isn't enough.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["burger", "beef", "hearty"],
  },
  {
    name: "Chicken Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 150,
    description: "Crispy chicken patty in a soft bun.",
    moods: ["hungry", "delicious", "budget"],
    tags: ["burger", "chicken"],
  },
  {
    name: "Pepperoni Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 200,
    description: "Classic pepperoni pizza — great for sharing.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["pizza", "shareable"],
  },
  {
    name: "Hawaiian Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 190,
    description: "Sweet pineapple meets savory ham.",
    moods: ["delicious", "hungry"],
    tags: ["pizza", "sweet-savory"],
  },
  {
    name: "Margherita Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 180,
    description: "Simple tomato, mozzarella, and basil.",
    moods: ["delicious", "healthy"],
    tags: ["pizza", "vegetarian"],
  },
  {
    name: "Ramen",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 220,
    description: "Rich broth, noodles, and toppings in one bowl.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["noodles", "japanese", "soup"],
  },
  {
    name: "Pancit Canton",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 120,
    description: "Stir-fried Filipino noodles loaded with toppings.",
    moods: ["hungry", "budget", "filling"],
    tags: ["noodles", "filipino", "pancit"],
  },
  {
    name: "Pancit Bihon",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 110,
    description: "Light rice noodles with vegetables and meat.",
    moods: ["hungry", "budget", "healthy"],
    tags: ["noodles", "filipino", "pancit"],
  },
  {
    name: "Beef Mami",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 130,
    description: "Warm noodle soup with tender beef.",
    moods: ["hungry", "filling", "budget"],
    tags: ["noodles", "soup", "filipino"],
  },
  {
    name: "Sushi Set",
    emoji: "🍣",
    category: "japanese",
    estimatedPricePerPerson: 280,
    description: "Assorted sushi rolls for a special treat.",
    moods: ["delicious", "hungry"],
    tags: ["japanese", "sushi", "seafood"],
  },
  {
    name: "Takoyaki",
    emoji: "🐙",
    category: "japanese",
    estimatedPricePerPerson: 150,
    description: "Crispy octopus balls with mayo and bonito.",
    moods: ["delicious", "hungry", "budget"],
    tags: ["japanese", "snack", "seafood"],
  },
  {
    name: "Tempura",
    emoji: "🍤",
    category: "japanese",
    estimatedPricePerPerson: 240,
    description: "Lightly battered and fried seafood and veggies.",
    moods: ["delicious", "hungry"],
    tags: ["japanese", "fried", "seafood"],
  },
  {
    name: "Chicken Teriyaki",
    emoji: "🍱",
    category: "japanese",
    estimatedPricePerPerson: 200,
    description: "Sweet-savory glazed chicken over rice.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["japanese", "chicken", "rice"],
  },
  {
    name: "Chicken Adobo Rice",
    emoji: "🍚",
    category: "filipino",
    estimatedPricePerPerson: 130,
    description: "Adobo with a generous serving of rice.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "chicken", "rice"],
  },
  {
    name: "Tapsilog",
    emoji: "🍳",
    category: "filipino",
    estimatedPricePerPerson: 140,
    description: "Tapa, sinangag, and itlog — the silog classic.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "silog", "breakfast"],
  },
  {
    name: "Tosilog",
    emoji: "🍳",
    category: "filipino",
    estimatedPricePerPerson: 130,
    description: "Tocino silog for a sweet-savory meal.",
    moods: ["hungry", "delicious", "budget"],
    tags: ["filipino", "silog", "pork"],
  },
  {
    name: "Longsilog",
    emoji: "🍳",
    category: "filipino",
    estimatedPricePerPerson: 120,
    description: "Longganisa with garlic rice and egg.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "silog", "pork"],
  },
  {
    name: "Siomai Rice",
    emoji: "🥟",
    category: "filipino",
    estimatedPricePerPerson: 90,
    description: "Steamed siomai over rice — cheap and filling.",
    moods: ["hungry", "budget", "filling"],
    tags: ["filipino", "siomai", "budget"],
  },
  {
    name: "Pork Sisig",
    emoji: "🔥",
    category: "filipino",
    estimatedPricePerPerson: 180,
    description: "Sizzling, spicy, and full of flavor.",
    moods: ["hungry", "spicy", "delicious"],
    tags: ["filipino", "spicy", "pork"],
  },
  {
    name: "Beef Tacos",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 190,
    description: "Soft tacos packed with seasoned beef.",
    moods: ["hungry", "delicious", "spicy"],
    tags: ["mexican", "taco", "beef"],
  },
  {
    name: "Chicken Quesadilla",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 170,
    description: "Cheesy tortilla filled with chicken.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["mexican", "chicken", "cheese"],
  },
  {
    name: "Nachos",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 160,
    description: "Crispy chips with toppings — shareable fun.",
    moods: ["delicious", "hungry", "budget"],
    tags: ["mexican", "snack", "shareable"],
  },
  {
    name: "Spaghetti",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 140,
    description: "Filipino-style sweet spaghetti or classic marinara.",
    moods: ["hungry", "filling", "budget"],
    tags: ["pasta", "filipino", "comfort"],
  },
  {
    name: "Carbonara",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 180,
    description: "Creamy pasta with bacon bits.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["pasta", "creamy"],
  },
  {
    name: "Lasagna",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 220,
    description: "Layered pasta with rich meat sauce and cheese.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["pasta", "hearty", "cheese"],
  },
  {
    name: "Garden Salad",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 150,
    description: "Fresh greens with a light dressing.",
    moods: ["healthy", "budget"],
    tags: ["healthy", "salad", "vegetarian"],
  },
  {
    name: "Chicken Caesar Salad",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 190,
    description: "Crisp romaine with grilled chicken and caesar dressing.",
    moods: ["healthy", "hungry", "delicious"],
    tags: ["healthy", "salad", "chicken"],
  },
  {
    name: "Poke Bowl",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 250,
    description: "Fresh fish, rice, and veggies in a colorful bowl.",
    moods: ["healthy", "delicious", "hungry"],
    tags: ["healthy", "seafood", "bowl"],
  },
  {
    name: "Spicy Wings",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 200,
    description: "Fiery chicken wings that bring the heat.",
    moods: ["spicy", "hungry", "delicious"],
    tags: ["spicy", "chicken", "wings"],
  },
  {
    name: "Spicy Ramen",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 230,
    description: "Ramen with an extra kick of chili.",
    moods: ["spicy", "hungry", "filling"],
    tags: ["spicy", "noodles", "japanese"],
  },
  {
    name: "Bicol Express",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 160,
    description: "Creamy coconut stew with chili and pork.",
    moods: ["spicy", "hungry", "filling"],
    tags: ["spicy", "filipino", "pork"],
  },
  {
    name: "Halo-Halo",
    emoji: "🍧",
    category: "dessert",
    estimatedPricePerPerson: 120,
    description: "The ultimate Filipino mixed dessert.",
    moods: ["sweet", "delicious", "budget"],
    tags: ["dessert", "filipino", "cold"],
  },
  {
    name: "Ice Cream Sundae",
    emoji: "🍦",
    category: "dessert",
    estimatedPricePerPerson: 100,
    description: "Cool, creamy, and customizable.",
    moods: ["sweet", "delicious", "budget"],
    tags: ["dessert", "ice-cream"],
  },
  {
    name: "Milk Tea",
    emoji: "🧋",
    category: "dessert",
    estimatedPricePerPerson: 90,
    description: "Sweet milk tea with pearls — a crowd favorite.",
    moods: ["sweet", "budget", "delicious"],
    tags: ["dessert", "drink", "milktea"],
  },
  {
    name: "Chocolate Cake",
    emoji: "🍰",
    category: "dessert",
    estimatedPricePerPerson: 140,
    description: "Rich chocolate cake for a sweet ending.",
    moods: ["sweet", "delicious"],
    tags: ["dessert", "cake", "chocolate"],
  },
  {
    name: "French Fries",
    emoji: "🍟",
    category: "sides",
    estimatedPricePerPerson: 80,
    description: "Crispy fries — the perfect side or snack.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["sides", "potato", "snack"],
  },
  {
    name: "Lomi",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 110,
    description: "Thick egg noodle soup, Batangas-style comfort.",
    moods: ["hungry", "filling", "budget"],
    tags: ["noodles", "filipino", "soup"],
  },
  {
    name: "Shawarma Rice",
    emoji: "🥙",
    category: "other",
    estimatedPricePerPerson: 130,
    description: "Seasoned meat over rice with garlic sauce.",
    moods: ["hungry", "filling", "budget"],
    tags: ["middle-eastern", "rice", "meat"],
  },
  {
    name: "Fish Balls & Kwek-Kwek",
    emoji: "🍢",
    category: "other",
    estimatedPricePerPerson: 50,
    description: "Street food classics on a stick.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["filipino", "streetfood", "budget"],
  },
  // --- Extra chicken ---
  {
    name: "Chicken BBQ",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 140,
    description: "Sweet-savory grilled chicken skewers.",
    moods: ["hungry", "delicious", "budget"],
    tags: ["chicken", "filipino", "grilled", "bbq"],
  },
  {
    name: "Chicken Curry",
    emoji: "🍛",
    category: "chicken",
    estimatedPricePerPerson: 160,
    description: "Creamy curry chicken with rice.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["chicken", "curry", "rice"],
  },
  {
    name: "Garlic Parmesan Wings",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 210,
    description: "Crispy wings tossed in garlic parmesan.",
    moods: ["hungry", "delicious"],
    tags: ["chicken", "wings", "shareable"],
  },
  {
    name: "Chicken Nuggets Meal",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 130,
    description: "Bite-sized nuggets with fries — easy crowd-pleaser.",
    moods: ["hungry", "budget", "filling"],
    tags: ["chicken", "fastfood", "nuggets"],
  },
  {
    name: "Buffalo Wings",
    emoji: "🌶️",
    category: "chicken",
    estimatedPricePerPerson: 200,
    description: "Tangy hot wings with a cool dip.",
    moods: ["spicy", "hungry", "delicious"],
    tags: ["chicken", "wings", "spicy"],
  },
  // --- Extra burger ---
  {
    name: "Bacon Cheeseburger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 200,
    description: "Classic burger stacked with crispy bacon.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["burger", "beef", "bacon"],
  },
  {
    name: "Mushroom Swiss Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 210,
    description: "Savory mushrooms and melted Swiss on a juicy patty.",
    moods: ["delicious", "hungry"],
    tags: ["burger", "beef", "mushroom"],
  },
  {
    name: "Fish Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 160,
    description: "Crispy fish fillet burger with tartar sauce.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["burger", "seafood", "fish"],
  },
  {
    name: "Veggie Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 170,
    description: "Plant-based patty for a lighter burger fix.",
    moods: ["healthy", "delicious"],
    tags: ["burger", "vegetarian", "healthy"],
  },
  // --- Extra pizza ---
  {
    name: "Meat Lovers Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 230,
    description: "Loaded with sausage, pepperoni, and ham.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["pizza", "meat", "shareable"],
  },
  {
    name: "BBQ Chicken Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 210,
    description: "Sweet BBQ sauce with chicken and onions.",
    moods: ["hungry", "delicious"],
    tags: ["pizza", "chicken", "bbq"],
  },
  {
    name: "Four Cheese Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 200,
    description: "Extra cheesy pizza for true cheese fans.",
    moods: ["delicious", "filling"],
    tags: ["pizza", "cheese", "vegetarian"],
  },
  {
    name: "Overloaded Supreme Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 240,
    description: "Veggies, meats, and cheese in every slice.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["pizza", "shareable", "supreme"],
  },
  // --- Extra noodles ---
  {
    name: "Beef Pho",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 200,
    description: "Fragrant broth with rice noodles and beef.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["noodles", "soup", "vietnamese"],
  },
  {
    name: "Pad Thai",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 190,
    description: "Sweet-savory stir-fried Thai noodles.",
    moods: ["hungry", "delicious"],
    tags: ["noodles", "thai", "stir-fry"],
  },
  {
    name: "Japchae",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 180,
    description: "Korean glass noodles with veggies and meat.",
    moods: ["delicious", "hungry"],
    tags: ["noodles", "korean", "stir-fry"],
  },
  {
    name: "Sotanghon Soup",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 100,
    description: "Warm glass noodle soup — light but comforting.",
    moods: ["hungry", "budget", "filling"],
    tags: ["noodles", "filipino", "soup"],
  },
  {
    name: "Yakisoba",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 170,
    description: "Japanese stir-fried noodles with savory sauce.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["noodles", "japanese", "stir-fry"],
  },
  // --- Extra japanese ---
  {
    name: "Katsu Curry",
    emoji: "🍱",
    category: "japanese",
    estimatedPricePerPerson: 250,
    description: "Crispy pork cutlet over rice with Japanese curry.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["japanese", "pork", "curry", "rice"],
  },
  {
    name: "Salmon Donburi",
    emoji: "🍚",
    category: "japanese",
    estimatedPricePerPerson: 260,
    description: "Salmon over seasoned rice in a hearty bowl.",
    moods: ["delicious", "hungry", "healthy"],
    tags: ["japanese", "seafood", "rice", "bowl"],
  },
  {
    name: "Gyoza",
    emoji: "🥟",
    category: "japanese",
    estimatedPricePerPerson: 140,
    description: "Pan-fried dumplings with dipping sauce.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["japanese", "dumpling", "snack"],
  },
  {
    name: "Chicken Karaage",
    emoji: "🍗",
    category: "japanese",
    estimatedPricePerPerson: 180,
    description: "Japanese-style crispy fried chicken bites.",
    moods: ["hungry", "delicious"],
    tags: ["japanese", "chicken", "fried"],
  },
  {
    name: "Udon Bowl",
    emoji: "🍜",
    category: "japanese",
    estimatedPricePerPerson: 190,
    description: "Thick wheat noodles in a savory broth.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["japanese", "noodles", "soup"],
  },
  // --- Extra filipino ---
  {
    name: "Sinigang na Baboy",
    emoji: "🍲",
    category: "filipino",
    estimatedPricePerPerson: 170,
    description: "Sour tamarind soup with pork and veggies.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["filipino", "soup", "pork"],
  },
  {
    name: "Kare-Kare",
    emoji: "🥜",
    category: "filipino",
    estimatedPricePerPerson: 220,
    description: "Peanut stew with oxtail and vegetables.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["filipino", "stew", "peanut"],
  },
  {
    name: "Lechon Kawali",
    emoji: "🐷",
    category: "filipino",
    estimatedPricePerPerson: 200,
    description: "Crispy fried pork belly — crunchy and rich.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["filipino", "pork", "fried"],
  },
  {
    name: "Chicken Tinola",
    emoji: "🍲",
    category: "filipino",
    estimatedPricePerPerson: 140,
    description: "Ginger chicken soup with green papaya.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "chicken", "soup"],
  },
  {
    name: "Bangus Silog",
    emoji: "🍳",
    category: "filipino",
    estimatedPricePerPerson: 150,
    description: "Fried milkfish with garlic rice and egg.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "silog", "seafood"],
  },
  {
    name: "Lumpia Shanghai",
    emoji: "🥟",
    category: "filipino",
    estimatedPricePerPerson: 100,
    description: "Crispy spring rolls packed with savory filling.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["filipino", "fried", "shareable"],
  },
  {
    name: "Pork BBQ Skewers",
    emoji: "🍢",
    category: "filipino",
    estimatedPricePerPerson: 120,
    description: "Charcoal-grilled sweet pork barbecue.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["filipino", "bbq", "pork", "streetfood"],
  },
  {
    name: "Bulalo",
    emoji: "🍲",
    category: "filipino",
    estimatedPricePerPerson: 250,
    description: "Beef bone marrow soup — rich and filling.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["filipino", "soup", "beef"],
  },
  // --- Extra mexican ---
  {
    name: "Beef Burrito",
    emoji: "🌯",
    category: "mexican",
    estimatedPricePerPerson: 200,
    description: "Wrapped tortilla stuffed with beef, rice, and beans.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["mexican", "burrito", "beef"],
  },
  {
    name: "Chicken Fajitas",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 220,
    description: "Sizzling chicken with peppers — build your own wraps.",
    moods: ["hungry", "delicious", "spicy"],
    tags: ["mexican", "chicken", "shareable"],
  },
  {
    name: "Fish Tacos",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 190,
    description: "Crispy fish tacos with slaw and lime.",
    moods: ["delicious", "hungry"],
    tags: ["mexican", "taco", "seafood"],
  },
  {
    name: "Chili Con Carne",
    emoji: "🌶️",
    category: "mexican",
    estimatedPricePerPerson: 180,
    description: "Hearty spiced beef chili — warm and filling.",
    moods: ["hungry", "spicy", "filling"],
    tags: ["mexican", "spicy", "beef"],
  },
  // --- Extra pasta ---
  {
    name: "Bolognese",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 190,
    description: "Slow-simmered meat sauce over pasta.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["pasta", "beef", "italian"],
  },
  {
    name: "Pesto Pasta",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 180,
    description: "Bright basil pesto coating every strand.",
    moods: ["delicious", "healthy"],
    tags: ["pasta", "pesto", "vegetarian"],
  },
  {
    name: "Seafood Pasta",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 240,
    description: "Pasta tossed with shrimp and mixed seafood.",
    moods: ["delicious", "hungry"],
    tags: ["pasta", "seafood", "shrimp"],
  },
  {
    name: "Aglio e Olio",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 150,
    description: "Simple garlic and oil pasta — light but tasty.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["pasta", "garlic", "vegetarian"],
  },
  {
    name: "Baked Macaroni",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 160,
    description: "Cheesy baked mac — Filipino party classic.",
    moods: ["hungry", "filling", "budget"],
    tags: ["pasta", "filipino", "cheese"],
  },
  // --- Extra healthy ---
  {
    name: "Grilled Salmon Salad",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 260,
    description: "Fresh greens topped with grilled salmon.",
    moods: ["healthy", "delicious", "hungry"],
    tags: ["healthy", "salad", "seafood"],
  },
  {
    name: "Buddha Bowl",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 200,
    description: "Balanced bowl of grains, veggies, and protein.",
    moods: ["healthy", "filling", "delicious"],
    tags: ["healthy", "bowl", "vegetarian"],
  },
  {
    name: "Chicken Avocado Wrap",
    emoji: "🌯",
    category: "healthy",
    estimatedPricePerPerson: 180,
    description: "Lean chicken wrap with creamy avocado.",
    moods: ["healthy", "hungry", "delicious"],
    tags: ["healthy", "chicken", "wrap"],
  },
  {
    name: "Vegetable Stir-Fry",
    emoji: "🥦",
    category: "healthy",
    estimatedPricePerPerson: 140,
    description: "Colorful veggies quickly wok-fried.",
    moods: ["healthy", "budget"],
    tags: ["healthy", "vegetarian", "vegetables"],
  },
  {
    name: "Tofu Bowl",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 160,
    description: "Crispy tofu with rice and fresh toppings.",
    moods: ["healthy", "budget", "filling"],
    tags: ["healthy", "tofu", "vegetarian", "bowl"],
  },
  // --- Extra spicy ---
  {
    name: "Spicy Fried Chicken",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 190,
    description: "Crispy chicken with a serious chili kick.",
    moods: ["spicy", "hungry", "delicious"],
    tags: ["spicy", "chicken", "fried"],
  },
  {
    name: "Kimchi Fried Rice",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 160,
    description: "Fiery kimchi rice, often topped with a fried egg.",
    moods: ["spicy", "hungry", "budget"],
    tags: ["spicy", "korean", "rice"],
  },
  {
    name: "Tom Yum",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 200,
    description: "Hot and sour Thai soup with shrimp.",
    moods: ["spicy", "hungry", "delicious"],
    tags: ["spicy", "thai", "soup", "seafood"],
  },
  {
    name: "Spicy Sisig",
    emoji: "🔥",
    category: "spicy",
    estimatedPricePerPerson: 190,
    description: "Extra-chili sisig for heat seekers.",
    moods: ["spicy", "hungry", "delicious"],
    tags: ["spicy", "filipino", "pork"],
  },
  {
    name: "Mapo Tofu",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 170,
    description: "Numbing-spicy Sichuan tofu over rice.",
    moods: ["spicy", "hungry", "filling"],
    tags: ["spicy", "tofu", "chinese"],
  },
  // --- Extra dessert ---
  {
    name: "Leche Flan",
    emoji: "🍮",
    category: "dessert",
    estimatedPricePerPerson: 90,
    description: "Silky caramel custard — a Filipino classic.",
    moods: ["sweet", "delicious", "budget"],
    tags: ["dessert", "filipino", "custard"],
  },
  {
    name: "Turon",
    emoji: "🍌",
    category: "dessert",
    estimatedPricePerPerson: 60,
    description: "Crispy banana spring rolls with caramelized sugar.",
    moods: ["sweet", "budget", "delicious"],
    tags: ["dessert", "filipino", "streetfood"],
  },
  {
    name: "Mango Float",
    emoji: "🥭",
    category: "dessert",
    estimatedPricePerPerson: 120,
    description: "Creamy layered mango dessert — chilled and sweet.",
    moods: ["sweet", "delicious"],
    tags: ["dessert", "filipino", "mango"],
  },
  {
    name: "Churros",
    emoji: "🍩",
    category: "dessert",
    estimatedPricePerPerson: 110,
    description: "Cinnamon-sugar sticks with chocolate dip.",
    moods: ["sweet", "delicious", "budget"],
    tags: ["dessert", "fried", "snack"],
  },
  {
    name: "Brownie Sundae",
    emoji: "🍫",
    category: "dessert",
    estimatedPricePerPerson: 150,
    description: "Warm brownie topped with ice cream.",
    moods: ["sweet", "delicious"],
    tags: ["dessert", "chocolate", "ice-cream"],
  },
  {
    name: "Fruit Smoothie",
    emoji: "🥤",
    category: "dessert",
    estimatedPricePerPerson: 100,
    description: "Blended fresh fruit drink — sweet and refreshing.",
    moods: ["sweet", "healthy", "budget"],
    tags: ["dessert", "drink", "fruit"],
  },
  // --- Extra sides / other ---
  {
    name: "Onion Rings",
    emoji: "🧅",
    category: "sides",
    estimatedPricePerPerson: 90,
    description: "Golden fried onion rings — great for sharing.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["sides", "fried", "snack"],
  },
  {
    name: "Mozzarella Sticks",
    emoji: "🧀",
    category: "sides",
    estimatedPricePerPerson: 120,
    description: "Gooey cheese sticks with marinara.",
    moods: ["hungry", "delicious"],
    tags: ["sides", "cheese", "fried"],
  },
  {
    name: "Garlic Bread",
    emoji: "🍞",
    category: "sides",
    estimatedPricePerPerson: 80,
    description: "Toasty bread with garlic butter.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["sides", "bread", "garlic"],
  },
  {
    name: "Siopao",
    emoji: "🥟",
    category: "other",
    estimatedPricePerPerson: 70,
    description: "Steamed bun stuffed with savory filling.",
    moods: ["hungry", "budget", "filling"],
    tags: ["filipino", "siopao", "snack"],
  },
  {
    name: "Chicken Empanada",
    emoji: "🥟",
    category: "other",
    estimatedPricePerPerson: 80,
    description: "Flaky pastry pocket filled with chicken.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["filipino", "chicken", "snack"],
  },
  {
    name: "Bibimbap",
    emoji: "🍚",
    category: "other",
    estimatedPricePerPerson: 220,
    description: "Korean rice bowl with veggies, egg, and gochujang.",
    moods: ["hungry", "delicious", "spicy"],
    tags: ["korean", "rice", "bowl", "spicy"],
  },
  {
    name: "Dim Sum Set",
    emoji: "🥟",
    category: "other",
    estimatedPricePerPerson: 240,
    description: "Assorted dumplings and small plates to share.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["chinese", "dumpling", "shareable"],
  },
  {
    name: "Paella",
    emoji: "🥘",
    category: "other",
    estimatedPricePerPerson: 280,
    description: "Saffron rice with seafood and meat — made for groups.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["spanish", "rice", "seafood", "shareable"],
  },
  // --- Steak & grilled meats ---
  {
    name: "Ribeye Steak",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 450,
    description: "Juicy ribeye with rich marbling — a proper steak night.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["steak", "beef", "grilled"],
  },
  {
    name: "Sirloin Steak",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 380,
    description: "Lean sirloin steak grilled to your liking.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["steak", "beef", "grilled"],
  },
  {
    name: "T-Bone Steak",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 520,
    description: "Big T-bone with tenderloin and strip in one cut.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["steak", "beef", "grilled", "shareable"],
  },
  {
    name: "Steak Frites",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 400,
    description: "Classic steak with a pile of crispy fries.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["steak", "beef", "fries"],
  },
  {
    name: "Pepper Steak",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 420,
    description: "Steak with creamy peppercorn sauce.",
    moods: ["hungry", "delicious", "spicy"],
    tags: ["steak", "beef", "pepper"],
  },
  {
    name: "Garlic Butter Steak",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 410,
    description: "Seared steak finished with garlic butter.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["steak", "beef", "garlic"],
  },
  {
    name: "Steak Rice Bowl",
    emoji: "🍚",
    category: "other",
    estimatedPricePerPerson: 250,
    description: "Sliced steak over rice — hearty without the full steakhouse bill.",
    moods: ["hungry", "filling", "budget"],
    tags: ["steak", "beef", "rice", "bowl"],
  },
  {
    name: "Bistek Tagalog",
    emoji: "🥩",
    category: "filipino",
    estimatedPricePerPerson: 180,
    description: "Soy-calamansi beef steak with onions — Filipino comfort.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "steak", "beef"],
  },
  {
    name: "Salpicao",
    emoji: "🥩",
    category: "filipino",
    estimatedPricePerPerson: 220,
    description: "Garlicky cubed beef steak, great with rice.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["filipino", "steak", "beef", "garlic"],
  },
  {
    name: "Beef Steak Sandwich",
    emoji: "🥪",
    category: "other",
    estimatedPricePerPerson: 230,
    description: "Thin-sliced steak piled into a warm sandwich.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["steak", "beef", "sandwich"],
  },
  // --- More chicken ---
  {
    name: "Honey Garlic Chicken",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 170,
    description: "Sticky sweet-savory chicken glazed with honey garlic.",
    moods: ["delicious", "hungry", "filling"],
    tags: ["chicken", "sweet-savory", "glazed"],
  },
  {
    name: "Chicken Parmigiana",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 240,
    description: "Breaded chicken with marinara and melted cheese.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["chicken", "italian", "cheese"],
  },
  {
    name: "Chicken Satay",
    emoji: "🍢",
    category: "chicken",
    estimatedPricePerPerson: 150,
    description: "Grilled chicken skewers with peanut sauce.",
    moods: ["hungry", "delicious", "budget"],
    tags: ["chicken", "grilled", "skewers"],
  },
  {
    name: "Orange Chicken",
    emoji: "🍊",
    category: "chicken",
    estimatedPricePerPerson: 180,
    description: "Crispy chicken in a bright orange glaze.",
    moods: ["hungry", "delicious"],
    tags: ["chicken", "sweet", "chinese"],
  },
  {
    name: "Chicken Biryani",
    emoji: "🍛",
    category: "chicken",
    estimatedPricePerPerson: 200,
    description: "Fragrant spiced rice layered with chicken.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["chicken", "rice", "indian"],
  },
  // --- More burger ---
  {
    name: "Smash Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 180,
    description: "Thin crispy-edged patties with melty cheese.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["burger", "beef", "smash"],
  },
  {
    name: "BBQ Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 200,
    description: "Burger topped with BBQ sauce and onion rings.",
    moods: ["hungry", "delicious"],
    tags: ["burger", "beef", "bbq"],
  },
  {
    name: "Truffle Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 280,
    description: "Upscale burger with truffle mayo and cheese.",
    moods: ["delicious", "hungry"],
    tags: ["burger", "beef", "truffle"],
  },
  {
    name: "Slider Trio",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 220,
    description: "Three mini burgers — perfect for sharing tastes.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["burger", "shareable", "sliders"],
  },
  // --- More pizza ---
  {
    name: "Truffle Mushroom Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 250,
    description: "Earthy mushrooms with a hint of truffle.",
    moods: ["delicious", "hungry"],
    tags: ["pizza", "mushroom", "truffle", "vegetarian"],
  },
  {
    name: "Garlic Shrimp Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 260,
    description: "Garlic cream base topped with shrimp.",
    moods: ["delicious", "hungry"],
    tags: ["pizza", "seafood", "shrimp"],
  },
  {
    name: "Pesto Chicken Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 220,
    description: "Pesto, chicken, and mozzarella on a crisp crust.",
    moods: ["delicious", "hungry"],
    tags: ["pizza", "chicken", "pesto"],
  },
  {
    name: "Sicilian Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 210,
    description: "Thick square slices with a fluffy crust.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["pizza", "thick-crust", "shareable"],
  },
  // --- More noodles ---
  {
    name: "Dan Dan Noodles",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 180,
    description: "Spicy, nutty Sichuan noodles with minced meat.",
    moods: ["spicy", "hungry", "delicious"],
    tags: ["noodles", "spicy", "chinese"],
  },
  {
    name: "Beef Lo Mein",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 170,
    description: "Soft noodles stir-fried with beef and veggies.",
    moods: ["hungry", "filling", "budget"],
    tags: ["noodles", "beef", "chinese"],
  },
  {
    name: "Laksa",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 210,
    description: "Coconut curry noodle soup with a spicy kick.",
    moods: ["spicy", "hungry", "filling"],
    tags: ["noodles", "soup", "spicy", "malaysian"],
  },
  {
    name: "Mee Goreng",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 150,
    description: "Spicy stir-fried noodles with a sweet edge.",
    moods: ["hungry", "spicy", "budget"],
    tags: ["noodles", "spicy", "stir-fry"],
  },
  {
    name: "Cold Soba",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 160,
    description: "Chilled buckwheat noodles with dipping sauce.",
    moods: ["healthy", "delicious"],
    tags: ["noodles", "japanese", "cold"],
  },
  // --- More japanese ---
  {
    name: "Tonkatsu",
    emoji: "🍱",
    category: "japanese",
    estimatedPricePerPerson: 230,
    description: "Crispy breaded pork cutlet with tonkatsu sauce.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["japanese", "pork", "fried"],
  },
  {
    name: "Unagi Don",
    emoji: "🍚",
    category: "japanese",
    estimatedPricePerPerson: 320,
    description: "Grilled eel glazed in sweet soy over rice.",
    moods: ["delicious", "hungry"],
    tags: ["japanese", "seafood", "rice"],
  },
  {
    name: "Okonomiyaki",
    emoji: "🥞",
    category: "japanese",
    estimatedPricePerPerson: 190,
    description: "Savory Japanese pancake loaded with toppings.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["japanese", "savory", "shareable"],
  },
  {
    name: "Chirashi Bowl",
    emoji: "🍣",
    category: "japanese",
    estimatedPricePerPerson: 300,
    description: "Assorted sashimi scattered over sushi rice.",
    moods: ["delicious", "healthy", "hungry"],
    tags: ["japanese", "sushi", "seafood", "bowl"],
  },
  // --- More filipino ---
  {
    name: "Pancit Malabon",
    emoji: "🍜",
    category: "filipino",
    estimatedPricePerPerson: 140,
    description: "Thick rice noodles with seafood sauce and toppings.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "noodles", "seafood"],
  },
  {
    name: "Laing",
    emoji: "🍃",
    category: "filipino",
    estimatedPricePerPerson: 130,
    description: "Taro leaves in spicy coconut milk.",
    moods: ["spicy", "hungry", "budget"],
    tags: ["filipino", "spicy", "coconut"],
  },
  {
    name: "Dinuguan",
    emoji: "🍲",
    category: "filipino",
    estimatedPricePerPerson: 150,
    description: "Rich pork blood stew — best with puto.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["filipino", "pork", "stew"],
  },
  {
    name: "Chicken Afritada",
    emoji: "🍲",
    category: "filipino",
    estimatedPricePerPerson: 140,
    description: "Tomato-based chicken stew with potatoes and carrots.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "chicken", "stew"],
  },
  {
    name: "Menudo",
    emoji: "🍲",
    category: "filipino",
    estimatedPricePerPerson: 140,
    description: "Tomato pork stew with liver and veggies.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "pork", "stew"],
  },
  {
    name: "Crispy Pata",
    emoji: "🐷",
    category: "filipino",
    estimatedPricePerPerson: 280,
    description: "Deep-fried pork leg — crunchy skin, tender meat.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["filipino", "pork", "fried", "shareable"],
  },
  {
    name: "Ginataang Kalabasa",
    emoji: "🎃",
    category: "filipino",
    estimatedPricePerPerson: 110,
    description: "Squash and sitaw in creamy coconut milk.",
    moods: ["hungry", "budget", "healthy"],
    tags: ["filipino", "vegetarian", "coconut"],
  },
  // --- More mexican ---
  {
    name: "Carnitas Tacos",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 200,
    description: "Slow-cooked pork tacos with salsa and onion.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["mexican", "taco", "pork"],
  },
  {
    name: "Loaded Nacho Platter",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 180,
    description: "Chips buried under cheese, salsa, and toppings.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["mexican", "nachos", "shareable"],
  },
  {
    name: "Chimichanga",
    emoji: "🌯",
    category: "mexican",
    estimatedPricePerPerson: 210,
    description: "Deep-fried burrito — crispy outside, hearty inside.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["mexican", "burrito", "fried"],
  },
  {
    name: "Guacamole & Chips",
    emoji: "🥑",
    category: "mexican",
    estimatedPricePerPerson: 120,
    description: "Fresh guacamole with warm tortilla chips.",
    moods: ["delicious", "budget", "healthy"],
    tags: ["mexican", "snack", "avocado"],
  },
  // --- More pasta ---
  {
    name: "Shrimp Alfredo",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 250,
    description: "Creamy Alfredo pasta topped with shrimp.",
    moods: ["delicious", "hungry", "filling"],
    tags: ["pasta", "seafood", "creamy"],
  },
  {
    name: "Arrabbiata",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 160,
    description: "Spicy tomato pasta with chili heat.",
    moods: ["spicy", "hungry", "budget"],
    tags: ["pasta", "spicy", "tomato", "vegetarian"],
  },
  {
    name: "Mushroom Risotto",
    emoji: "🍚",
    category: "pasta",
    estimatedPricePerPerson: 230,
    description: "Creamy Arborio rice with sautéed mushrooms.",
    moods: ["delicious", "filling", "hungry"],
    tags: ["pasta", "risotto", "mushroom", "vegetarian"],
  },
  {
    name: "Beef Stroganoff",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 240,
    description: "Tender beef in creamy sauce over noodles.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["pasta", "beef", "creamy"],
  },
  // --- More healthy ---
  {
    name: "Acai Bowl",
    emoji: "🫐",
    category: "healthy",
    estimatedPricePerPerson: 200,
    description: "Blended berries topped with granola and fruit.",
    moods: ["healthy", "sweet", "delicious"],
    tags: ["healthy", "bowl", "fruit"],
  },
  {
    name: "Quinoa Salad",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 180,
    description: "Protein-packed quinoa with fresh vegetables.",
    moods: ["healthy", "filling"],
    tags: ["healthy", "salad", "vegetarian"],
  },
  {
    name: "Grilled Chicken Bowl",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 190,
    description: "Lean grilled chicken with greens and grains.",
    moods: ["healthy", "hungry", "filling"],
    tags: ["healthy", "chicken", "bowl"],
  },
  {
    name: "Sushi Salad",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 220,
    description: "Deconstructed sushi flavors in a fresh bowl.",
    moods: ["healthy", "delicious"],
    tags: ["healthy", "seafood", "japanese", "bowl"],
  },
  {
    name: "Veggie Spring Rolls",
    emoji: "🥬",
    category: "healthy",
    estimatedPricePerPerson: 120,
    description: "Fresh rice-paper rolls with herbs and peanut dip.",
    moods: ["healthy", "budget", "delicious"],
    tags: ["healthy", "vegetarian", "fresh"],
  },
  // --- More spicy ---
  {
    name: "Spicy Tuna Roll",
    emoji: "🍣",
    category: "spicy",
    estimatedPricePerPerson: 200,
    description: "Sushi rolls with spicy tuna mayo.",
    moods: ["spicy", "delicious", "hungry"],
    tags: ["spicy", "japanese", "seafood", "sushi"],
  },
  {
    name: "Sambal Chicken",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 170,
    description: "Chicken cooked in fiery sambal chili paste.",
    moods: ["spicy", "hungry", "delicious"],
    tags: ["spicy", "chicken", "malaysian"],
  },
  {
    name: "Hot Pot",
    emoji: "🍲",
    category: "spicy",
    estimatedPricePerPerson: 300,
    description: "Communal spicy broth with meats and veggies.",
    moods: ["spicy", "hungry", "filling"],
    tags: ["spicy", "chinese", "shareable", "soup"],
  },
  {
    name: "Jalapeño Poppers",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 130,
    description: "Cheese-stuffed jalapeños, breaded and fried.",
    moods: ["spicy", "delicious", "budget"],
    tags: ["spicy", "snack", "fried", "cheese"],
  },
  // --- More dessert ---
  {
    name: "Ube Ice Cream",
    emoji: "🍦",
    category: "dessert",
    estimatedPricePerPerson: 100,
    description: "Creamy purple yam ice cream — Filipino favorite.",
    moods: ["sweet", "delicious", "budget"],
    tags: ["dessert", "filipino", "ice-cream", "ube"],
  },
  {
    name: "Cheesecake",
    emoji: "🍰",
    category: "dessert",
    estimatedPricePerPerson: 160,
    description: "Rich, creamy cheesecake slice.",
    moods: ["sweet", "delicious"],
    tags: ["dessert", "cake", "cheese"],
  },
  {
    name: "Tiramisu",
    emoji: "☕",
    category: "dessert",
    estimatedPricePerPerson: 180,
    description: "Coffee-soaked layers with mascarpone cream.",
    moods: ["sweet", "delicious"],
    tags: ["dessert", "coffee", "italian"],
  },
  {
    name: "Puto Bumbong",
    emoji: "🟣",
    category: "dessert",
    estimatedPricePerPerson: 80,
    description: "Purple sticky rice steamed in bamboo — festive treat.",
    moods: ["sweet", "budget", "delicious"],
    tags: ["dessert", "filipino", "rice"],
  },
  {
    name: "Crepes",
    emoji: "🥞",
    category: "dessert",
    estimatedPricePerPerson: 140,
    description: "Thin pancakes filled with sweet toppings.",
    moods: ["sweet", "delicious"],
    tags: ["dessert", "crepe", "sweet"],
  },
  {
    name: "Affogato",
    emoji: "🍨",
    category: "dessert",
    estimatedPricePerPerson: 120,
    description: "Vanilla ice cream drowned in hot espresso.",
    moods: ["sweet", "delicious"],
    tags: ["dessert", "coffee", "ice-cream"],
  },
  // --- More sides / other ---
  {
    name: "Loaded Fries",
    emoji: "🍟",
    category: "sides",
    estimatedPricePerPerson: 130,
    description: "Fries topped with cheese, sauce, and extras.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["sides", "potato", "shareable"],
  },
  {
    name: "Corn Ribs",
    emoji: "🌽",
    category: "sides",
    estimatedPricePerPerson: 110,
    description: "Seasoned corn “ribs” — fun and shareable.",
    moods: ["delicious", "budget"],
    tags: ["sides", "corn", "vegetarian"],
  },
  {
    name: "Calamari",
    emoji: "🦑",
    category: "sides",
    estimatedPricePerPerson: 180,
    description: "Crispy fried squid rings with dipping sauce.",
    moods: ["hungry", "delicious"],
    tags: ["sides", "seafood", "fried"],
  },
  {
    name: "Poke Nachos",
    emoji: "🐟",
    category: "other",
    estimatedPricePerPerson: 240,
    description: "Crispy chips piled with poke toppings.",
    moods: ["delicious", "hungry"],
    tags: ["seafood", "poke", "shareable"],
  },
  {
    name: "Lamb Chops",
    emoji: "🍖",
    category: "other",
    estimatedPricePerPerson: 480,
    description: "Grilled lamb chops with herbs and sides.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["lamb", "grilled", "steak"],
  },
  {
    name: "Prime Rib",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 550,
    description: "Slow-roasted prime rib — carve-and-share energy.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["steak", "beef", "roast", "shareable"],
  },
  {
    name: "Tomahawk Steak",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 700,
    description: "Showpiece bone-in steak for a special group meal.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["steak", "beef", "grilled", "shareable"],
  },
  {
    name: "Beef Wellington",
    emoji: "🥩",
    category: "other",
    estimatedPricePerPerson: 600,
    description: "Beef tenderloin wrapped in pastry — special occasion.",
    moods: ["delicious", "filling", "hungry"],
    tags: ["steak", "beef", "pastry"],
  },
  {
    name: "Gyro Plate",
    emoji: "🥙",
    category: "other",
    estimatedPricePerPerson: 190,
    description: "Sliced gyro meat with pita, salad, and sauce.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["middle-eastern", "meat", "pita"],
  },
  {
    name: "Nasi Goreng",
    emoji: "🍚",
    category: "other",
    estimatedPricePerPerson: 150,
    description: "Indonesian fried rice with sweet-spicy kick.",
    moods: ["hungry", "budget", "spicy"],
    tags: ["rice", "indonesian", "spicy"],
  },
  {
    name: "Seafood Boil",
    emoji: "🦞",
    category: "other",
    estimatedPricePerPerson: 450,
    description: "Shrimp, crab, and corn in a spicy boil — messy fun.",
    moods: ["hungry", "filling", "spicy"],
    tags: ["seafood", "spicy", "shareable"],
  },
  {
    name: "Clam Chowder",
    emoji: "🥣",
    category: "other",
    estimatedPricePerPerson: 180,
    description: "Creamy clam soup — warm and comforting.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["seafood", "soup", "creamy"],
  },
];

async function main() {
  const prisma = new PrismaClient();

  console.log("Clearing existing foods...");
  await prisma.food.deleteMany();

  console.log("Seeding foods...");
  for (const food of foods) {
    await prisma.food.create({
      data: {
        name: food.name,
        emoji: food.emoji,
        category: food.category,
        estimatedPricePerPerson: food.estimatedPricePerPerson,
        description: food.description,
        moods: JSON.stringify(food.moods),
        tags: JSON.stringify(food.tags),
      },
    });
  }

  console.log(`Seeded ${foods.length} foods.`);
  await prisma.$disconnect();
}

main().catch(async (error) => {
  console.error(error);
  process.exit(1);
});
