import { PrismaClient } from "@prisma/client";

const foods = [
  {
    name: "Chicken Inasal",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 150,
    description: "Grilled chicken with a tangy marinade — a Filipino favorite.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["chicken", "filipino", "grilled"],
  },
  {
    name: "Roasted Chicken",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 180,
    description: "Classic roasted chicken — great for sharing with the group.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["chicken", "roasted", "shareable"],
  },
  {
    name: "Fried Chicken",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 180,
    description: "Crispy fried chicken that never disappoints.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["chicken", "fried", "comfort"],
  },
  {
    name: "Chicken Adobo",
    emoji: "🍲",
    category: "chicken",
    estimatedPricePerPerson: 140,
    description: "Classic Filipino adobo — savory, garlicky, and comforting.",
    moods: ["hungry", "filling", "budget"],
    tags: ["chicken", "filipino", "adobo"],
  },
  {
    name: "Chicken Joy",
    emoji: "🍗",
    category: "chicken",
    estimatedPricePerPerson: 160,
    description: "The iconic crispy chicken meal everyone knows.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["chicken", "fastfood"],
  },
  {
    name: "Cheeseburger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 170,
    description: "Juicy burger with cheese — simple and satisfying.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["burger", "beef", "fastfood"],
  },
  {
    name: "Double Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 220,
    description: "Two patties for when one just isn't enough.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["burger", "beef", "hearty"],
  },
  {
    name: "Chicken Burger",
    emoji: "🍔",
    category: "burger",
    estimatedPricePerPerson: 150,
    description: "Crispy chicken patty in a soft bun.",
    moods: ["hungry", "delicious", "budget"],
    tags: ["burger", "chicken"],
  },
  {
    name: "Pepperoni Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 200,
    description: "Classic pepperoni pizza — great for sharing.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["pizza", "shareable"],
  },
  {
    name: "Hawaiian Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 190,
    description: "Sweet pineapple meets savory ham.",
    moods: ["delicious", "hungry"],
    tags: ["pizza", "sweet-savory"],
  },
  {
    name: "Margherita Pizza",
    emoji: "🍕",
    category: "pizza",
    estimatedPricePerPerson: 180,
    description: "Simple tomato, mozzarella, and basil.",
    moods: ["delicious", "healthy"],
    tags: ["pizza", "vegetarian"],
  },
  {
    name: "Ramen",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 220,
    description: "Rich broth, noodles, and toppings in one bowl.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["noodles", "japanese", "soup"],
  },
  {
    name: "Pancit Canton",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 120,
    description: "Stir-fried Filipino noodles loaded with toppings.",
    moods: ["hungry", "budget", "filling"],
    tags: ["noodles", "filipino", "pancit"],
  },
  {
    name: "Pancit Bihon",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 110,
    description: "Light rice noodles with vegetables and meat.",
    moods: ["hungry", "budget", "healthy"],
    tags: ["noodles", "filipino", "pancit"],
  },
  {
    name: "Beef Mami",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 130,
    description: "Warm noodle soup with tender beef.",
    moods: ["hungry", "filling", "budget"],
    tags: ["noodles", "soup", "filipino"],
  },
  {
    name: "Sushi Set",
    emoji: "🍣",
    category: "japanese",
    estimatedPricePerPerson: 280,
    description: "Assorted sushi rolls for a special treat.",
    moods: ["delicious", "hungry"],
    tags: ["japanese", "sushi", "seafood"],
  },
  {
    name: "Takoyaki",
    emoji: "🐙",
    category: "japanese",
    estimatedPricePerPerson: 150,
    description: "Crispy octopus balls with mayo and bonito.",
    moods: ["delicious", "hungry", "budget"],
    tags: ["japanese", "snack", "seafood"],
  },
  {
    name: "Tempura",
    emoji: "🍤",
    category: "japanese",
    estimatedPricePerPerson: 240,
    description: "Lightly battered and fried seafood and veggies.",
    moods: ["delicious", "hungry"],
    tags: ["japanese", "fried", "seafood"],
  },
  {
    name: "Chicken Teriyaki",
    emoji: "🍱",
    category: "japanese",
    estimatedPricePerPerson: 200,
    description: "Sweet-savory glazed chicken over rice.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["japanese", "chicken", "rice"],
  },
  {
    name: "Chicken Adobo Rice",
    emoji: "🍚",
    category: "filipino",
    estimatedPricePerPerson: 130,
    description: "Adobo with a generous serving of rice.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "chicken", "rice"],
  },
  {
    name: "Tapsilog",
    emoji: "🍳",
    category: "filipino",
    estimatedPricePerPerson: 140,
    description: "Tapa, sinangag, and itlog — the silog classic.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "silog", "breakfast"],
  },
  {
    name: "Tosilog",
    emoji: "🍳",
    category: "filipino",
    estimatedPricePerPerson: 130,
    description: "Tocino silog for a sweet-savory meal.",
    moods: ["hungry", "delicious", "budget"],
    tags: ["filipino", "silog", "pork"],
  },
  {
    name: "Longsilog",
    emoji: "🍳",
    category: "filipino",
    estimatedPricePerPerson: 120,
    description: "Longganisa with garlic rice and egg.",
    moods: ["hungry", "filling", "budget"],
    tags: ["filipino", "silog", "pork"],
  },
  {
    name: "Siomai Rice",
    emoji: "🥟",
    category: "filipino",
    estimatedPricePerPerson: 90,
    description: "Steamed siomai over rice — cheap and filling.",
    moods: ["hungry", "budget", "filling"],
    tags: ["filipino", "siomai", "budget"],
  },
  {
    name: "Pork Sisig",
    emoji: "🔥",
    category: "filipino",
    estimatedPricePerPerson: 180,
    description: "Sizzling, spicy, and full of flavor.",
    moods: ["hungry", "spicy", "delicious"],
    tags: ["filipino", "spicy", "pork"],
  },
  {
    name: "Beef Tacos",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 190,
    description: "Soft tacos packed with seasoned beef.",
    moods: ["hungry", "delicious", "spicy"],
    tags: ["mexican", "taco", "beef"],
  },
  {
    name: "Chicken Quesadilla",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 170,
    description: "Cheesy tortilla filled with chicken.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["mexican", "chicken", "cheese"],
  },
  {
    name: "Nachos",
    emoji: "🌮",
    category: "mexican",
    estimatedPricePerPerson: 160,
    description: "Crispy chips with toppings — shareable fun.",
    moods: ["delicious", "hungry", "budget"],
    tags: ["mexican", "snack", "shareable"],
  },
  {
    name: "Spaghetti",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 140,
    description: "Filipino-style sweet spaghetti or classic marinara.",
    moods: ["hungry", "filling", "budget"],
    tags: ["pasta", "filipino", "comfort"],
  },
  {
    name: "Carbonara",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 180,
    description: "Creamy pasta with bacon bits.",
    moods: ["hungry", "delicious", "filling"],
    tags: ["pasta", "creamy"],
  },
  {
    name: "Lasagna",
    emoji: "🍝",
    category: "pasta",
    estimatedPricePerPerson: 220,
    description: "Layered pasta with rich meat sauce and cheese.",
    moods: ["hungry", "filling", "delicious"],
    tags: ["pasta", "hearty", "cheese"],
  },
  {
    name: "Garden Salad",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 150,
    description: "Fresh greens with a light dressing.",
    moods: ["healthy", "budget"],
    tags: ["healthy", "salad", "vegetarian"],
  },
  {
    name: "Chicken Caesar Salad",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 190,
    description: "Crisp romaine with grilled chicken and caesar dressing.",
    moods: ["healthy", "hungry", "delicious"],
    tags: ["healthy", "salad", "chicken"],
  },
  {
    name: "Poke Bowl",
    emoji: "🥗",
    category: "healthy",
    estimatedPricePerPerson: 250,
    description: "Fresh fish, rice, and veggies in a colorful bowl.",
    moods: ["healthy", "delicious", "hungry"],
    tags: ["healthy", "seafood", "bowl"],
  },
  {
    name: "Spicy Wings",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 200,
    description: "Fiery chicken wings that bring the heat.",
    moods: ["spicy", "hungry", "delicious"],
    tags: ["spicy", "chicken", "wings"],
  },
  {
    name: "Spicy Ramen",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 230,
    description: "Ramen with an extra kick of chili.",
    moods: ["spicy", "hungry", "filling"],
    tags: ["spicy", "noodles", "japanese"],
  },
  {
    name: "Bicol Express",
    emoji: "🌶️",
    category: "spicy",
    estimatedPricePerPerson: 160,
    description: "Creamy coconut stew with chili and pork.",
    moods: ["spicy", "hungry", "filling"],
    tags: ["spicy", "filipino", "pork"],
  },
  {
    name: "Halo-Halo",
    emoji: "🍧",
    category: "dessert",
    estimatedPricePerPerson: 120,
    description: "The ultimate Filipino mixed dessert.",
    moods: ["sweet", "delicious", "budget"],
    tags: ["dessert", "filipino", "cold"],
  },
  {
    name: "Ice Cream Sundae",
    emoji: "🍦",
    category: "dessert",
    estimatedPricePerPerson: 100,
    description: "Cool, creamy, and customizable.",
    moods: ["sweet", "delicious", "budget"],
    tags: ["dessert", "ice-cream"],
  },
  {
    name: "Milk Tea",
    emoji: "🧋",
    category: "dessert",
    estimatedPricePerPerson: 90,
    description: "Sweet milk tea with pearls — a crowd favorite.",
    moods: ["sweet", "budget", "delicious"],
    tags: ["dessert", "drink", "milktea"],
  },
  {
    name: "Chocolate Cake",
    emoji: "🍰",
    category: "dessert",
    estimatedPricePerPerson: 140,
    description: "Rich chocolate cake for a sweet ending.",
    moods: ["sweet", "delicious"],
    tags: ["dessert", "cake", "chocolate"],
  },
  {
    name: "French Fries",
    emoji: "🍟",
    category: "sides",
    estimatedPricePerPerson: 80,
    description: "Crispy fries — the perfect side or snack.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["sides", "potato", "snack"],
  },
  {
    name: "Lomi",
    emoji: "🍜",
    category: "noodles",
    estimatedPricePerPerson: 110,
    description: "Thick egg noodle soup, Batangas-style comfort.",
    moods: ["hungry", "filling", "budget"],
    tags: ["noodles", "filipino", "soup"],
  },
  {
    name: "Shawarma Rice",
    emoji: "🥙",
    category: "other",
    estimatedPricePerPerson: 130,
    description: "Seasoned meat over rice with garlic sauce.",
    moods: ["hungry", "filling", "budget"],
    tags: ["middle-eastern", "rice", "meat"],
  },
  {
    name: "Fish Balls & Kwek-Kwek",
    emoji: "🍢",
    category: "other",
    estimatedPricePerPerson: 50,
    description: "Street food classics on a stick.",
    moods: ["hungry", "budget", "delicious"],
    tags: ["filipino", "streetfood", "budget"],
  },
];

async function main() {
  const prisma = new PrismaClient();

  console.log("Clearing existing foods...");
  await prisma.food.deleteMany();

  console.log("Seeding foods...");
  for (const food of foods) {
    await prisma.food.create({
      data: {
        name: food.name,
        emoji: food.emoji,
        category: food.category,
        estimatedPricePerPerson: food.estimatedPricePerPerson,
        description: food.description,
        moods: JSON.stringify(food.moods),
        tags: JSON.stringify(food.tags),
      },
    });
  }

  console.log(`Seeded ${foods.length} foods.`);
  await prisma.$disconnect();
}

main().catch(async (error) => {
  console.error(error);
  process.exit(1);
});
